-- JAMAAT-APP-2026 Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.ward_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('News','Notice')),
  title text not null check (char_length(title) between 1 and 150),
  date date not null,
  description text not null check (char_length(description) between 1 and 5000),
  status text not null default 'pending' check (status in ('pending','published')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null
);

create index if not exists ward_items_status_date_idx
  on public.ward_items(status, date desc, created_at desc);

alter table public.ward_items enable row level security;

-- Public users can read published content only.
drop policy if exists "public_read_published" on public.ward_items;
create policy "public_read_published"
  on public.ward_items for select
  to anon, authenticated
  using (status = 'published');

-- Logged-in users can submit their own pending content.
drop policy if exists "users_insert_pending" on public.ward_items;
create policy "users_insert_pending"
  on public.ward_items for insert
  to authenticated
  with check (
    created_by = auth.uid()
    and status = 'pending'
  );

-- Logged-in users may delete their own pending submissions.
drop policy if exists "users_delete_own_pending" on public.ward_items;
create policy "users_delete_own_pending"
  on public.ward_items for delete
  to authenticated
  using (created_by = auth.uid() and status = 'pending');

-- Admin approval is intentionally NOT granted to every authenticated user.
-- Create an admin role/profile and a restricted policy before enabling browser-side approval.
-- Never put the Supabase service_role key in this repository or in browser JavaScript.

-- Optional admin table for role management.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "users_read_own_profile" on public.profiles;
create policy "users_read_own_profile"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

-- IMPORTANT: After creating your first admin Auth user, promote it manually in SQL:
-- update public.profiles set role='admin' where id='YOUR-AUTH-USER-UUID';

-- Admin policies use a SECURITY DEFINER helper to avoid recursive RLS checks.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admins_read_all" on public.ward_items;
create policy "admins_read_all"
  on public.ward_items for select
  to authenticated
  using (public.is_admin());

drop policy if exists "admins_update_items" on public.ward_items;
create policy "admins_update_items"
  on public.ward_items for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "admins_delete_items" on public.ward_items;
create policy "admins_delete_items"
  on public.ward_items for delete
  to authenticated
  using (public.is_admin());
