-- JAMAAT-APP-2026 Supabase schema

create table if not exists public.ward_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('News','Notice')),
  title text not null check (char_length(title) between 1 and 150),
  date date not null,
  description text not null check (char_length(description) between 1 and 5000),
  status text not null default 'pending' check (status in ('pending','published')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null
);

create index if not exists ward_items_status_date_idx on public.ward_items(status, date desc, created_at desc);
alter table public.ward_items enable row level security;

drop policy if exists "public_read_published" on public.ward_items;
create policy "public_read_published" on public.ward_items for select to anon, authenticated using (status = 'published');

drop policy if exists "users_insert_pending" on public.ward_items;
create policy "users_insert_pending" on public.ward_items for insert to authenticated with check (created_by = auth.uid() and status = 'pending');

drop policy if exists "users_delete_own_pending" on public.ward_items;
create policy "users_delete_own_pending" on public.ward_items for delete to authenticated using (created_by = auth.uid() and status = 'pending');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "users_read_own_profile" on public.profiles;
create policy "users_read_own_profile" on public.profiles for select to authenticated using (id = auth.uid());

-- The first Auth account becomes admin; later accounts are normal users.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if not exists (select 1 from public.profiles) then
    insert into public.profiles(id, role) values(new.id, 'admin');
  else
    insert into public.profiles(id, role) values(new.id, 'user');
  end if;
  return new;
end;
$$;
revoke all on function public.handle_new_user() from public;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admins_read_all" on public.ward_items;
create policy "admins_read_all" on public.ward_items for select to authenticated using (public.is_admin());

drop policy if exists "admins_update_items" on public.ward_items;
create policy "admins_update_items" on public.ward_items for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins_delete_items" on public.ward_items;
create policy "admins_delete_items" on public.ward_items for delete to authenticated using (public.is_admin());

-- Never put a service_role/secret key in browser code or this repository.
