-- STEP 8: Member verification / organization access
-- This project currently uses Supabase (see push.js/admin.html), not Firebase.

create table if not exists public.member_verification_requests (
  id bigint generated by default as identity primary key,
  applicant_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  position_title text,
  phone text not null,
  blood_group text not null check (blood_group in ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  photo_url text,
  comment text,
  branch text not null check (branch in ('male','female')),
  division text not null,
  district text not null,
  thana text not null,
  ward integer not null check (ward between 1 and 50),
  unit_name text not null,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  organization_access boolean not null default false,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.organization_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  request_id bigint not null references public.member_verification_requests(id) on delete cascade,
  title text not null,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- Add scope columns when the existing profiles table is present.
alter table if exists public.profiles add column if not exists organization_role text;
alter table if exists public.profiles add column if not exists organization_branch text;
alter table if exists public.profiles add column if not exists organization_division text;
alter table if exists public.profiles add column if not exists organization_district text;
alter table if exists public.profiles add column if not exists organization_thana text;
alter table if exists public.profiles add column if not exists organization_ward integer;
alter table if exists public.profiles add column if not exists organization_unit text;

create or replace function public.can_review_member_request(p_request_id bigint)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.member_verification_requests r on r.id = p_request_id
    where p.id = auth.uid()
      and p.organization_role in ('unit','ward','thana','district','division','national','admin')
      and (
        p.organization_role in ('national','admin')
        or (p.organization_role='division' and p.organization_division=r.division and p.organization_branch=r.branch)
        or (p.organization_role='district' and p.organization_district=r.district and p.organization_branch=r.branch)
        or (p.organization_role='thana' and p.organization_thana=r.thana and p.organization_district=r.district and p.organization_branch=r.branch)
        or (p.organization_role='ward' and p.organization_ward=r.ward and p.organization_thana=r.thana and p.organization_district=r.district and p.organization_branch=r.branch)
        or (p.organization_role='unit' and p.organization_unit=r.unit_name and p.organization_ward=r.ward and p.organization_thana=r.thana and p.organization_district=r.district and p.organization_branch=r.branch)
      )
  );
$$;

alter table public.member_verification_requests enable row level security;
alter table public.organization_notifications enable row level security;

drop policy if exists "member requests insert own" on public.member_verification_requests;
create policy "member requests insert own" on public.member_verification_requests
for insert to authenticated
with check (applicant_id = auth.uid());

drop policy if exists "member requests read own or reviewer" on public.member_verification_requests;
create policy "member requests read own or reviewer" on public.member_verification_requests
for select to authenticated
using (applicant_id = auth.uid() or public.can_review_member_request(id));

drop policy if exists "member requests reviewer update" on public.member_verification_requests;
create policy "member requests reviewer update" on public.member_verification_requests
for update to authenticated
using (public.can_review_member_request(id))
with check (public.can_review_member_request(id));

drop policy if exists "notifications recipient read" on public.organization_notifications;
create policy "notifications recipient read" on public.organization_notifications
for select to authenticated
using (recipient_id = auth.uid());

drop policy if exists "notifications recipient update" on public.organization_notifications;
create policy "notifications recipient update" on public.organization_notifications
for update to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

create or replace function public.notify_member_reviewers()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.organization_notifications(recipient_id, request_id, title, body)
  select p.id, new.id, 'নতুন সদস্য যাচাই আবেদন',
         new.full_name || ' সদস্যপদ যাচাইয়ের জন্য আবেদন করেছেন।'
  from public.profiles p
  where p.organization_role in ('ward','thana','district','division','national','admin')
    and (
      p.organization_role in ('national','admin')
      or (p.organization_role='division' and p.organization_division=new.division and p.organization_branch=new.branch)
      or (p.organization_role='district' and p.organization_district=new.district and p.organization_branch=new.branch)
      or (p.organization_role='thana' and p.organization_thana=new.thana and p.organization_district=new.district and p.organization_branch=new.branch)
      or (p.organization_role='ward' and p.organization_ward=new.ward and p.organization_thana=new.thana and p.organization_district=new.district and p.organization_branch=new.branch)
    );
  return new;
end;
$$;

drop trigger if exists member_review_notification on public.member_verification_requests;
create trigger member_review_notification
after insert on public.member_verification_requests
for each row execute function public.notify_member_reviewers();

-- On acceptance organization access becomes active; rejection keeps general app access.
create or replace function public.set_member_access()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'accepted' then
    new.organization_access := true;
  elsif new.status = 'rejected' then
    new.organization_access := false;
  end if;
  if new.status <> 'pending' and (old.status is distinct from new.status) then
    new.reviewed_by := auth.uid();
    new.reviewed_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists member_access_status on public.member_verification_requests;
create trigger member_access_status
before update of status on public.member_verification_requests
for each row execute function public.set_member_access();
