-- Production hardening for JAMAAT APP 2026.
-- Secret values are intentionally NOT stored in Git. Production keeps them in Supabase Vault.

create extension if not exists pg_net;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;
drop policy if exists push_users_read_own on public.push_subscriptions;
create policy push_users_read_own on public.push_subscriptions for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists push_users_insert_own on public.push_subscriptions;
create policy push_users_insert_own on public.push_subscriptions for insert to authenticated with check (user_id = (select auth.uid()));
drop policy if exists push_anon_insert on public.push_subscriptions;
create policy push_anon_insert on public.push_subscriptions for insert to anon with check (user_id is null);
drop policy if exists push_users_update_own on public.push_subscriptions;
create policy push_users_update_own on public.push_subscriptions for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
drop policy if exists push_users_delete_own on public.push_subscriptions;
create policy push_users_delete_own on public.push_subscriptions for delete to authenticated using (user_id = (select auth.uid()));

create index if not exists ward_items_created_by_idx on public.ward_items(created_by);
create index if not exists services_created_by_idx on public.services(created_by);
create index if not exists committee_members_created_by_idx on public.committee_members(created_by);
create index if not exists gallery_items_created_by_idx on public.gallery_items(created_by);
create index if not exists documents_created_by_idx on public.documents(created_by);
create index if not exists help_items_created_by_idx on public.help_items(created_by);

-- Consolidated authenticated read policies: published content is public, admins can also see pending rows.
drop policy if exists services_public_read on public.services;
drop policy if exists services_admin_read on public.services;
create policy services_public_read on public.services for select to anon using (status='published');
drop policy if exists services_auth_read on public.services;
create policy services_auth_read on public.services for select to authenticated using (status='published' or is_admin());
drop policy if exists committee_public_read on public.committee_members;
drop policy if exists committee_admin_read on public.committee_members;
create policy committee_public_read on public.committee_members for select to anon using (status='published');
drop policy if exists committee_auth_read on public.committee_members;
create policy committee_auth_read on public.committee_members for select to authenticated using (status='published' or is_admin());
drop policy if exists gallery_public_read on public.gallery_items;
drop policy if exists gallery_admin_read on public.gallery_items;
create policy gallery_public_read on public.gallery_items for select to anon using (status='published');
drop policy if exists gallery_auth_read on public.gallery_items;
create policy gallery_auth_read on public.gallery_items for select to authenticated using (status='published' or is_admin());
drop policy if exists documents_public_read on public.documents;
drop policy if exists documents_admin_read on public.documents;
create policy documents_public_read on public.documents for select to anon using (status='published');
drop policy if exists documents_auth_read on public.documents;
create policy documents_auth_read on public.documents for select to authenticated using (status='published' or is_admin());
drop policy if exists help_public_read on public.help_items;
drop policy if exists help_admin_read on public.help_items;
create policy help_public_read on public.help_items for select to anon using (status='published');
drop policy if exists help_auth_read on public.help_items;
create policy help_auth_read on public.help_items for select to authenticated using (status='published' or is_admin());
drop policy if exists public_read_published on public.ward_items;
drop policy if exists admins_read_all on public.ward_items;
create policy ward_public_read on public.ward_items for select to anon using (status='published');
drop policy if exists ward_auth_read on public.ward_items;
create policy ward_auth_read on public.ward_items for select to authenticated using (status='published' or is_admin());

-- Push configuration is stored in Vault under these names:
-- jamaat_vapid_private_key
-- jamaat_push_webhook_secret
create or replace function public.get_push_config(p_secret text)
returns table(private_key text)
language plpgsql security definer set search_path = public, vault
as $$
begin
  if p_secret is null then return; end if;
  if not exists (select 1 from vault.decrypted_secrets where name='jamaat_push_webhook_secret' and decrypted_secret=p_secret) then return; end if;
  return query select decrypted_secret from vault.decrypted_secrets where name='jamaat_vapid_private_key' limit 1;
end;
$$;
revoke all on function public.get_push_config(text) from public;

create or replace function public.notify_new_published_ward_item()
returns trigger language plpgsql security definer set search_path = public, vault, net
as $$
declare secret text; private_key text;
begin
  if new.status <> 'published' or old.status = 'published' then return new; end if;
  select decrypted_secret into secret from vault.decrypted_secrets where name='jamaat_push_webhook_secret' limit 1;
  select decrypted_secret into private_key from vault.decrypted_secrets where name='jamaat_vapid_private_key' limit 1;
  if secret is null or private_key is null then return new; end if;
  perform net.http_post(
    url := 'https://pgwxfccpphjjveoeeqhv.supabase.co/functions/v1/send-push-v2',
    headers := jsonb_build_object('Content-Type','application/json','x-jamaat-push-secret',secret),
    body := jsonb_build_object('privateKey',private_key,'title',case when new.type='Notice' then '📢 নতুন নোটিশ' else '📰 নতুন নিউজ' end,'message',new.title,'url','./news.html' || case when new.type='Notice' then '#notice' else '' end,'tag','ward-' || new.type)
  );
  return new;
end;
$$;
revoke all on function public.notify_new_published_ward_item() from public;
drop trigger if exists ward_item_push_notification on public.ward_items;
create trigger ward_item_push_notification after update of status on public.ward_items for each row execute function public.notify_new_published_ward_item();
